name = "anizen"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[vars]
VITE_IMAGE_PROXY_ENABLED = "false"
VITE_ANIMEKAI_PROXY = "https://anizen-api-production.up.railway.app/anikai"
VITE_MAINTENANCE_MODE = "false"
VITE_POCKETBASE_URL = "https://pocketbase-anizen.up.railway.app/"